python nesnelere dayalı bir dil. fonksiyonlar bile nesnedir. kendi klaslarımızı oluşturmamız gerekmiyor. hazır nesnelere var.

In [3]:
import numpy as np
import time
import sys

In [4]:
my_tuple= 1,2,3,4,5
my_first_array=np.array(my_tuple)
my_first_array  # bu çıkan array objecttir

array([1, 2, 3, 4, 5])

In [5]:
np.size(my_first_array)

5

In [6]:
my_first_array=np.append(my_first_array,(6,7))
my_first_array

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
np.size(my_first_array)

7

In [8]:
listem=[1,2,3]
id(listem)   #listeler ekleme yapınca id değişmiyor.

1225881686272

In [10]:
id(my_first_array)

1225899300112

In [11]:
listem.append(4)
listem

[1, 2, 3, 4]

In [12]:
id(listem)

1225881686272

In [13]:
my_first_array=np.append(my_first_array,(8,9))
my_first_array  # np de ise array eklenince id değişiyor.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
id(my_first_array)

1225899300688

In [17]:
listem=[3,"üç",True, 6.0,(1,2,3), {"1":1,"2":2}]
for i in range(len(listem)):
    print(f" data {i+1}: {listem[i]}) -- tiipi :{type(listem[i])}")

 data 1: 3) -- tiipi :<class 'int'>
 data 2: üç) -- tiipi :<class 'str'>
 data 3: True) -- tiipi :<class 'bool'>
 data 4: 6.0) -- tiipi :<class 'float'>
 data 5: (1, 2, 3)) -- tiipi :<class 'tuple'>
 data 6: {'1': 1, '2': 2}) -- tiipi :<class 'dict'>


In [18]:
listem_tektip=[1,2,3]
np.array(listem_tektip)

array([1, 2, 3])

In [19]:
np.array(listem_tektip).dtype


dtype('int32')

In [20]:
listem_farklı=[1,2,3.0]
np.array(listem_farklı)   #h hemen hepsi float oldu bak.

array([1., 2., 3.])

In [21]:
np.array(listem_farklı).dtype

dtype('float64')

In [22]:
listem_karışık=[1,"2",3.0]
array3=np.array(listem_karışık)
array3

array(['1', '2', '3.0'], dtype='<U32')

In [23]:
import numpy as np
 
a = np.array([1, 2, 3])   # 1 boyutlu bir array
print(type(a))            # Veri türü
print(a.shape)            # Array şekli
print(a[0], a[1], a[2])   # Array öğrelerine erişim
a[0] = 5                  # Array'in bir elemanını değiştirme
print(a)                  # Tüm elemanları yazdırma
 
b = np.array([[1,2,3],[4,5,6]])    # İki boyutlu bir rray
print(b.shape)                     # Array şekli 
print(b[0, 0], b[0, 1], b[1, 0])   # Öğelere erişim

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [24]:
import numpy as np
 
a = np.zeros((2,2))   # Tüm elemanları 0 olan 2'ye 2 bir array
print(a)
b = np.ones((1,2))    # Tüm elemanları bir olan 1'e 2 bir array
print(b)            
c = np.full((2,2), 7)  # Sabit bir değerden oluşan array
print(c)
d = np.eye(2)         # 2x2'lik birim matrix
print(d)
e = np.random.random((2,2))  # 2x2'lik rastgele elemanlardan oluşan bir matrix
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.98350022 0.4763302 ]
 [0.87564365 0.35769773]]


In [25]:
dt = np.dtype([('yas',np.int8)]) 
print(dt)
dt = np.dtype([('yas',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)
dt = np.dtype([('yas',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['yas'])
ogrenci = np.dtype([('name','S20'), ('yas', 'i1'), ('marks', 'f4')]) 
print(ogrenci)
ogrenci = np.dtype([('name','S20'), ('yas', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = ogrenci) 
print(a)

[('yas', 'i1')]
[(10,) (20,) (30,)]
[10 20 30]
[('name', 'S20'), ('yas', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [26]:
a = np.arange(15).reshape(3, 5) #arange sıralı bir dizi oluşturur, reshape bu diziye tekrar şekil verir: 3x5'lik
print(a)
print(a.shape)
print(a.ndim) #boyut(dimension) sayısı, shape'deki eleman sayısı
print(a.dtype.name) #veri tipi, dikkat edildiyse veri tipi verilmedi ama otomatik olarak belirlenir
print(a.itemsize) #öğe boyutu, bit değeri / 8, örneğin int64 için 64 / 8
print(type(a)) #veri tipi ama a nesnesinin, öğelerin değil

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
<class 'numpy.ndarray'>


In [27]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
print(a)
print(b)
print(c)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [28]:
a = np.array( [[1,1],[0,1]] )
b = np.array( [[2,0],[3,4]] )
print(a)
print(b)
print(a*b)
print(a@b)
print(a.dot(b))

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [35]:
d3=np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]])

In [33]:
import seaborn as sbr

In [40]:
np.array(d3)

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [3]:
import numpy as np

In [4]:
a = np.random.randint(10, size = (2, 3)) 
b = np.random.randint(10, size = (2, 3))

In [5]:
a

array([[2, 9, 2],
       [7, 4, 3]])

In [6]:
b

array([[7, 8, 3],
       [9, 3, 3]])

In [7]:
a,b

(array([[2, 9, 2],
        [7, 4, 3]]),
 array([[7, 8, 3],
        [9, 3, 3]]))

In [8]:
np.concatenate((a,b), axis=0)

array([[2, 9, 2],
       [7, 4, 3],
       [7, 8, 3],
       [9, 3, 3]])

In [13]:
np.concatenate((a,b), axis=1)

array([[2, 9, 2, 7, 8, 3],
       [7, 4, 3, 9, 3, 3]])

In [14]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

In [19]:
x,y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [21]:
np.concatenate([x,y], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [22]:
np.concatenate([x,y], axis=1)   # neye göre birlşetirmek istiyorsak eşitleme lazım.

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [24]:
x=np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [26]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [27]:
a,b,c= np.split(x,[3,5])

In [28]:
a

array([1, 2, 3])

In [29]:
b

array([99, 99])

In [30]:
c

array([3, 2, 1])

In [31]:
a,b,c,d= np.split(x,[3,5])

ValueError: not enough values to unpack (expected 4, got 3)

In [32]:
np.split(x,[4])    #4.indexten böl demek bu.

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [35]:
np.split(x,4)

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

In [10]:
m = np.arange(20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
np.split(m,[1,3],axis=0)   # satırlardan böler.

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [38]:
np.split(m,[1,3],axis=1) 

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [39]:
np.split(m,[1,2,3],axis=0)  

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [11]:
np.vsplit(m,[1,3])    #index numaralarını vertikel olarak say demek

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [50]:
left,right =np.hsplit(m,[2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [51]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [42]:
np.vsplit(m,[3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [12]:
upper,lower =np.vsplit(m,[3])

In [13]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [15]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [17]:
v.sort() 
v   #yerinde değiştirir. print vermese bile

array([1, 2, 3, 4, 5])

In [18]:
v

array([1, 2, 3, 4, 5])

In [67]:
twoD = np.random.randint(5, 100, (3, 3))

In [68]:
twoD

array([[44, 11, 72],
       [50, 65, 84],
       [95, 83, 36]])

In [69]:
np.sort(twoD,axis=0)  

array([[44, 11, 36],
       [50, 65, 72],
       [95, 83, 84]])

In [70]:
np.sort(twoD,axis=1)

array([[11, 44, 72],
       [50, 65, 84],
       [36, 83, 95]])

In [71]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[8]

8

In [73]:
arr[-3]

8

In [74]:
arr[1:5]

array([1, 2, 3, 4])

In [75]:
arr[:5]

array([0, 1, 2, 3, 4])

In [76]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [77]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

In [78]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d [1]

array([20, 25, 30])

In [83]:
arr_2d [1,1]

25

In [84]:
arr_2d[1][1]

25

In [85]:
type(arr_2d[1][1])

numpy.int32

In [86]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [87]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [91]:
arr_2d [2,:2]

array([35, 40])

In [102]:
arr_2d [1,1]

25

In [95]:
arr_2d[2,0]

35

In [149]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [97]:
v[1]

3

In [98]:
v[3]

9

In [99]:
v[5]

15

In [ ]:
#birden fazla index numarası göndermek istiyorusam liste halinde girmemiz lazım

In [100]:
index_list=[1,3,7]
v[index_list]

array([ 3,  9, 21])

In [103]:
arr2d = np.zeros((10, 10), dtype=int) 

In [104]:
arr2d 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [107]:
arr2d.shape

(10, 10)

In [108]:
arr2d.shape[0]

10

In [110]:
for x in range(arr2d.shape[0]):  # her satıra 0 kalacak diğerlerine 1,2,3,4,5,6,7,8,9 u atamak için for yaptık.
    arr2d[x]=x                   # ben olsam harfleri yapardım. satır ile index karışıyor.
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [111]:
arr2d[3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [114]:
arr2d[[7,4,9]]

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [118]:
jj= np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [120]:
jj[1,0]

5

In [123]:
jj[[1,2],[0,3]]

array([ 5, 12])

In [126]:
jj[[1,2,0],[0,3,1]]

array([ 5, 12,  2])

In [127]:
jj[[1,1],[1,3]]

array([6, 8])

In [128]:
jj[1,[1,3]]

array([6, 8])

In [129]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [133]:
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
jj[]

In [136]:
jj[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [137]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [138]:
condition=arr>4     #selection yaptık.

In [139]:
arr[condition]  #selection of condition yaptık

array([ 5,  6,  7,  8,  9, 10])

In [143]:
arr[arr<6]

array([0, 1, 2, 3, 4, 5])

In [144]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
arr[(arr!=3) & (arr !=4)]

array([ 0,  1,  2,  5,  6,  7,  8,  9, 10])

In [146]:
arr [((arr<3) | (arr>8)) & ((arr!=9) & (arr !=2))]

array([ 0,  1, 10])

In [151]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
arr[:5]=77
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [155]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
slice_of_arr=arr[0:6]
slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [157]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [158]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [160]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
arr + arr   #vectrization

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [162]:
arr *arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [163]:
arr /arr   # yaptı ama kızardı.

C:\Users\tuna\AppData\Local\Temp\ipykernel_2320\591710190.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr /arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [164]:
import warnings
warnings.filterwarnings('ignore')   # uyarı kodu verdiği zaman bu kodu çalıştırız.

In [165]:
arr /arr   

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [166]:
1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [167]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [168]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [169]:
np.subtract(arr,1) #herbirinden 1 çıkardı

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [170]:
np.add(arr,2)  # herbirine 2 ekledi. yine vectroizitain özelliği

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [171]:
np.power(arr,3)  #herbirinin 3. kuvveti

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [174]:
np.mod(arr[arr>3 ],2)

array([0, 1, 0, 1, 0, 1], dtype=int32)

In [175]:
x1 = np.arange(9.0).reshape(3, 3)
x2 = np.arange(3.0)

In [176]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [177]:
x2

array([0., 1., 2.])

In [178]:
np.subtract(x1,x2)  #her satırdan  x2 yi çıkardı.

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [179]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [181]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [182]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [183]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [185]:
np.log10(1000)

3.0

In [186]:
np.mean(arr)

4.5

In [188]:
arr.mean()

4.5

In [190]:
arry = np.array([4,7,1,9,1,2,6,8,10])
arry

array([ 4,  7,  1,  9,  1,  2,  6,  8, 10])

In [191]:
np.median(arry)

6.0

In [192]:
arry.std()

3.265986323710904

In [193]:
arry.sum()

48

In [200]:
np.random.seed(42)
xarr=np.random.randn(3,5)

In [201]:
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])