In [1]:
import numpy
import numpy
import SciPy
import Seaborn
import Matplotlib


ModuleNotFoundError: No module named 'NumPy'

In [24]:
import numpy as np

In [3]:
import pandas


In [14]:
from scipy import stats

In [13]:
import seaborn

In [7]:
import matplotlib

In [8]:
print(numpy.__version__)

1.21.5


In [9]:
print(pandas.__version__)

1.4.2


In [10]:
print(scipy.__version__)

1.7.3


In [11]:
print(seaborn.__version__)

0.11.2


In [12]:
print(matplotlib.__version__)

3.5.1


In [20]:
a= [5,7,10,15,19,21,21,22,22,23,23,23,23,23,24,24,24,24,25]

In [17]:
len (a)

19

In [22]:
import statistics
print("mod değeri :" , statistics.mode(a))
print("ortalama değeri : " ,statistics.mean(a))
print("ortanca değeri : " ,statistics.median(a))
print("varyans değeri : " ,statistics.variance(a))
print("standart sapma değeri : " ,statistics.pstdev(a))

mod değeri : 23
ortalama değeri :  19.894736842105264
ortanca değeri :  23
varyans değeri :  36.87719298245614
standart sapma değeri :  5.910692691101667


In [25]:
np.mean(a)

19.894736842105264

In [26]:
stats.mode(a)

ModeResult(mode=array([23]), count=array([5]))

In [27]:
stats.mode(a)[0]

array([23])

In [28]:
stats.mode(a)[0][0]

23

In [29]:
np.min(a)

5

In [30]:
np.max(a)

25

In [38]:
q1=np.percentile(a,25) 
q1 #q1

20.0

In [40]:
q3=np.percentile(a,75) #q3
q3


23.5

In [41]:
iqr=q3-q1
iqr

3.5

In [42]:
stats.iqr(a)

3.5

In [36]:
np.percentile(a,50)

23.0

In [44]:
np.percentile(a,[25,50,75,100])

array([20. , 23. , 23.5, 25. ])

In [45]:
my_list = [5,7,10,15,19,21,21,22,22,23,23,23,23,23,24,24,24,24,25]

print("Q1", np.percentile(my_list,[25]))
print("Q2", np.percentile(my_list,[50]))
print("Q3", np.percentile(my_list,[75]))
print("IQR", stats.iqr(my_list))
print("MİN", np.percentile(my_list,[25]) - 1.5*stats.iqr(my_list))
print("MAX", np.percentile(my_list,[75]) + 1.5*stats.iqr(my_list))

Q1 [20.]
Q2 [23.]
Q3 [23.5]
IQR 3.5
MİN [14.75]
MAX [28.75]


In [46]:
np.var(a) #varyans

34.93628808864266

In [47]:
np.std(a) #standart sapma

5.910692691101667

In [48]:
np.sqrt(np.var(a))

5.910692691101667

In [49]:
stats.skew(a)  #sola çarpık

-1.5176315809887007

In [50]:
numpy.histogram_bin_edges(a, bins=10, range=None, weights=None)

array([ 5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.])

In [52]:
numpy.digitize(a, q1, right=False)

ValueError: object of too small depth for desired array

In [57]:
import seaborn

In [58]:
seaborn.lineplot(ax=a)

[5, 7, 10, 15, 19, 21, 21, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 25]